version: '3.5'

services:
  main:
    container_name: main
    build:
      context: .
    env_file: 
      - .${NODE_ENV:-production}.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 5000:5000
      - 7000:7000
    depends_on:
      - postgres
    command: sh -c "if [ \"$NODE_ENV\" = \"development\" ]; then npm run start:dev; else npm run start:prod; fi"
    restart: always 
  postgres:
    container_name: postgres
    image: postgres:12
    env_file: 
      - .${NODE_ENV:-production}.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports: 
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:

